---
title: "Bootcamps (Tier 1)"
---

## BATS Bootcamp in Summer 2024

**Dates**: July 15 - 19, 2024

**Location**: Vassar College, Poughkeepsie, NY

**Expected number of participants**: 20

**Funding**: All bootcamp participants (20) will be supported with a stipend of $2,000 each to offset costs of traveling to and accommodation during the bootcamp.

**Application details**: The application form will be shared here in early 2024.

**Questions** can be addressed to Monika Hu at [jihu@vassar.edu](mailto:jihu@vassar.edu).

## BATS Bootcamp in Summer 2023

**Schedule:** [link](https://bayes-bats.github.io/bootcamp-material/)

**GitHub organization:** [link](https://github.com/bayes-bats)

**Dates**: July 10 - 14, 2023

**Location**: University of California Irvine

**Expected number of participants**: 20

**Funding**: All bootcamp participants (20) will be supported with a stipend of $2,000 each to offset costs of traveling to and accommodation during the bootcamp.

**Application details**: The application form can be accessed at [this link](https://duke.qualtrics.com/jfe/form/SV_2sDimvyrSaeAl1A). Applications are due **February 15, 2023**. Applications are only open to US citizens and permanent residents.

**Questions** can be addressed to Mine Dogucu at [mdogucu@uci.edu](mailto:mdogucu@uci.edu).

---


