---
title: "Dissemination (Tier 3)"
---

We would like the teaching materials developed by BATS instructors to reach a wider audience beyond their own students. We would like these resources to be adopted by their colleagues in their STEM fields. 

We expect to support about five instructors each year in writing pedagogical papers and/or giving conference talks within their scientific discipline community, introducing their developed materials as well as discussing Bayesian pedagogy. 

We expect these efforts to be aimed at more pedagogy-focused channels such as journals and conferences focusing on science education. 

Instructors selected for the dissemination group will be supported with $2,000 each to disseminate their work at national conferences and/or with open-access publications.

# Tier 3 - Dissemination News

## Publications

[Langehennig, S., del Rosario, Z., & Dogucu, M. Surprise, They’re Different! Comparing Frequentist and Bayesian Instructional Approaches in Political Science and Public Policy Classrooms. Political Science Educator. 29(1)](https://educate.apsanet.org/surprise-theyre-different-comparing-frequentist-and-bayesian-instructional-approaches-in-political-science-and-public-policy-classrooms)

## Presentations

Table last updated on 2024-05-20.

| Date | Name | Title | Venue |  Links |
|------|------|-------|-------|-------|
| 2024-03-01 |Toni Sorrell|Shaping Tomorrow's Innovators: Integrating Bayesian Concepts into STEM Pedagogy|Virginia Association of Mathematics Teacher Educators (VA-AMTE)|  [{{< fa note-sticky >}}](tier3/abstract-sorrell.html)    |
|2024-04-06| Stefani Langehennig | Surprise-They’re Different! Comparing Frequentist and Bayesian Approaches in Public Policy |Midwest Political Science Association Conference |[{{< fa desktop >}}](tier3/slides-langehennig.html)|
|2024-05-15| Stefani Langehennig | Comparing Frequentist and Bayesian Approaches in Policy Learning | Conference on Policy Process Research ||
|2024-05-30|Patricia Toledo | Introducing Frequentist and Bayesian Methods in Parallel in an Undergraduate Economics Statistics Course | The Thirteenth Annual AEA Conference on Teaching and Research in Economic Education (CTREE) | |
|2024-06-12|Angela Ebeling | POGIL-style Activities Introducing Students to Bayes Theorem| Electronic Conference on Teaching Statistics |[{{< fa video >}}](https://www.causeweb.org/cause/ecots/ecots24/program/posters/6) |
|TBD 2024-07-01 - 2024-07-07| Patricia Toledo | Introducing Frequentist and Bayesian Methods in Parallel in an Undergraduate Economics Statistics Course | International Society for Bayesian Analysis World Meeting |   [{{< fa note-sticky >}}](tier3/abstract-toledo.html)|
|2024-08-04|Samantha Seals |Embracing Bayesian Statistics in the Modern Classroom | Joint Statistical Meetings| |
|2024-08-04| Kaitlyn Fitzgerald |Inquiry Based Learning activities for teaching Bayesian statistics|Joint Statistical Meetings ||
|2024-08-04|Patricia Toledo |Introducing Frequentist and Bayesian Methods in Parallel in an Undergraduate Economics Statistics Course|Joint Statistical Meetings||
|2024-08-04|Zachary del Rosario|Surprise—they're different! An introductory statistics activity to highlight differences between Frequentist and Bayesian statistics| Joint Statistical Meetings ||


## Other BATS related Publications

[Kejzlar, V., & Hu, J. (2023). Introducing Variational Inference in Statistics and Data Science Curriculum. The American Statistician, 78(3), 359–367. https://doi.org/10.1080/00031305.2023.2232006](https://www.tandfonline.com/doi/citedby/10.1080/00031305.2023.2232006?scroll=top&needAccess=true)

[Dogucu, M., Kazak, S. & Rosenberg, J. (2025) The Design and Implementation of a Bayesian Data Analysis Lesson for Pre-Service Mathematics and Science Teachers. Journal of Statistics and Data Science Education. 33(2), 177-188.](https://www.tandfonline.com/doi/full/10.1080/26939169.2024.2362148)

[Dogucu, M., Hu, J., & Herring, A. H. (2025). Statisticians Training STEM Educators in Statistics Methods and Pedagogy: A Case Study of Instructor Training in Bayesian Methods. arXiv preprint arXiv:2505.02298.](https://arxiv.org/abs/2505.02298)
