---
title: "Course Materials Development (Tier 2)"
---

## Description

About ten instructors **who attend the bootcamp** will be selected to develop course materials in the Fall semester. They will be engaged in a semester-long collaborative endeavor to develop teaching and learning materials of Bayesian methods for undergraduate students in their disciplines that are at public dissemination quality. Instructors of similar STEM disciplines will be teamed up, and each team is mentored by one of the PIs. Depending on the instructor’s objective and their plan of introducing Bayesian methods in their undergraduate curriculum, we expect some to develop a **Bayesian module** to be part of an existing course while others to develop a **full Bayesian course** as part of their curriculum offerings. 

## Funding

Instructors selected to participate in course material development will be compensated with $1,500 each for their time and effort.  

## Application

All participants in the BATS Bootcamp in Summer 2024 are eligible to apply to Tier 2 by an application. The application is closed.

## Schedule

The schedule of Tier 2 activities for the 2024 cohort can be found at [this link](https://bayes-bats.github.io/tier2-schedule-2024/).

## Example Course Materials

The following are some of the teaching materials that Bayes BATS participants have developed. 


<table class="table table-bordered">

<thead>
<td> Project Cohort</td>
<td> Project Title</td>
<td> Project Participants</td>
<td> Materials</td>

</thead>

  <tr>
  <td> 2023 </td>
  <td> Surprise!---They're Different &nbsp; </td>
    <td>
    Zachary del Rosario <br>
    Stefani Langehennig  &nbsp;
    </td>
    
    <td>
    
   [{{< fa brands github >}}](https://github.com/bayes-bats/tier2-freq-bayes)
 [{{< fa video >}}](https://www.youtube.com/watch?v=dwNLcFqQqnE)
    </td>
</td>
  </tr>
  
  <tr>
  <td> 2023 </td>
  <td> POGIL-style activities:
  Introductions to Bayesian Statistics &nbsp; </td>
    <td>
    Olga Glebova <br>
    Kaitlyn Fitzgerald  &nbsp;
    Angela Ebeling
    </td>
    
    <td>
    
   [{{< fa folder >}}](https://drive.google.com/drive/folders/1gFeNNysCFKF2yTehxUSu-pzq-iaCx44f?usp=sharing)
 [{{< fa video >}}](https://urldefense.com/v3/__https://drive.google.com/file/d/1g3VLUrxF4Y_S8IDu9BrWvIt3VJI5wR-n/view?usp=sharing__;!!CzAuKJ42GuquVTTmVmPViYEvSg!LSWPSJol80NXTPLLVrWKrBBi1C6bvGH8In6gd1SJpQCuGJqyTDAEwJpzzwKcbQ3z-c1D7UiJvupb4qt0hJAS$)
    </td>
</td>
  </tr>

  <tr>
  <td> 2023 </td>
  <td> Bayesian Thinking: Course Materials for Bayesian Topics &nbsp; </td>
    <td>
    Abraham Ayebo <br>
    Samantha Seals <br>
    Toni Sorrell &nbsp;
    </td>
    
    <td>
    
   [{{< fa link >}}](https://bayes-thinking.github.io/website/)
 [{{< fa video >}}](https://drive.google.com/file/d/1Rw4orsrz2-U4aHxjGSPvqga-0dMrFvJd/view?usp=sharing)
    </td>
</td>
  </tr>
  
  <tr>
  <td> 2023 </td>
  <td> Introducing Frequentist and Bayesian Methods in Parallel in an
Undergraduate Economics Statistics Course &nbsp; </td>
    <td>
    Patricia Toledo &nbsp;
    </td>
    
    <td>
    
   [{{< fa link >}}](https://drive.google.com/file/d/1uv8pQFa_OUI-wjKQpiXN1N9phYhiaH8L/view?usp=sharing)
   [{{< fa video >}}](https://drive.google.com/file/d/1nCOIMgj9Tn5lTjc0KPMZq3jWpoyROebV/view?usp=sharing)
    </td>
</td>
  </tr>
  
  <tr>
  <td> 2024 </td>
  <td> Introductory Bayes In Context &nbsp; </td>
    <td>
    Adam Gilbert <br>
    Laura Lambert  &nbsp;
    </td>
    
    <td>
    
   [{{< fa link >}}](https://agmath.github.io/IntroductoryBayesInContext/)
 [{{< fa video >}}](https://www.youtube.com/watch?v=3-1gnfEkUXA)
    </td>
</td>
  </tr>
  
   <tr>
  <td> 2024 </td>
  <td> Bayesian Thinking in BSMEs &nbsp; </td>
    <td>
    Tom Keenan &nbsp;
    </td>
    
    <td>
    
   [{{< fa link >}}](https://www.dropbox.com/scl/fi/b9xgs2w3qnd5km53kj6wi/Bayesian-Thinking-for-BSMEs-Final-Progress-Report.pdf?rlkey=brsdiqn7y305qp60s09aamoox&st=yndrj58m&dl=0)
 [{{< fa video >}}](https://www.dropbox.com/scl/fi/d4juxctmsea58jfqs8tfz/Bayesian-Thinking-for-BSMEs-Final-Report.mp4?rlkey=dxmwuivsbhv16rtos975edj2z&st=w997s7fj&dl=0)
    </td>
</td>
  </tr>
  
  
  <tr>
  <td> 2024 </td>
  <td> TBD &nbsp; </td>
    <td>
    Adam Scharfenberger &nbsp;
    </td>
    
    <td>
   [{{< fa folder >}}](https://drive.google.com/drive/folders/1mUVw9ECx260iBaUW1z8qABOoYqWDM2kP?usp=sharing)
   [{{< fa video >}}](https://drive.google.com/file/d/1OKRe-RhVw0s6S8GtNArqBkIB-ETy36TL/view?usp=sharing)
    </td>
</td>
  </tr>
  
  
  <tr>
  <td> 2024 </td>
  <td> Introduction to Statistical Storytelling: A 1-Week Module in Bayesian Thinking &nbsp; </td>
    <td>
    Christopher Wolfe &nbsp;
    </td>
    
    <td>
    
   [{{< fa brands github >}}](https://github.com/bayes-bats/tier2-anthro)
    [{{< fa video >}}](https://ecu.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=c7d6204a-9ea6-4e49-a2da-b24300fde86d)
    </td>
</td>
  </tr>
  
  
  <tr>
  <td> 2024 </td>
  <td> A Gentle Introduction to Probability and Bayesian Statistics &nbsp; </td>
    <td>
    Laurie Baker <br>
    Jim Scott  &nbsp;
    </td>
    
    <td>
    
   [{{< fa brands github >}}](https://bayes-bats.github.io/tier2-short-term/)
 [{{< fa video >}}](https://www.dropbox.com/s/9oqg1lqhja3p7jm/bayes-bats.mp4?st=0gcuuf97&dl=0)
    </td>
</td>
  </tr>
  
  
</table>

<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
