---
title: "People"
---

## Directors / Principal Investigators 

- [Mine Dogucu](https://www.minedogucu.com/); Assistant Professor of Teaching Statistics, University of California Irvine 

- [Jingchen (Monika) Hu](https://pages.vassar.edu/jihu/); Associate Professor of Mathematics and Statistics, Vassar College

- [Amy Herring](https://scholars.duke.edu/person/Amy.Herring); Sara and Charles Ayres Distinguished Professor of Statistical Science, Duke University 


## Advisory Board

- Andrew Gelman; Professor of Statistics and Political Science, Columbia University
- Donna LaLonde; Director Strategic Initiatives and Outreach, American Statistical Association
- Regina Nuzzo; Professor of Statistics, Gallaudet University
- Donatello Telesca; Professor of Biostatistics, University of California Los Angeles


## Supporting Faculty

- Ming-Wen An; Associate Professor of Mathematics and Statistics, Vassar 
- Josh de Leeuw; Assistant Professor of Cognitive Science, Vassar 
- David Dunson; Professor of Statistical Science, Mathematics and Electrical & Computer Engineering, Duke University 
- Matthew Harding; Professor of Economics and Statistics, UCI 
- Lee Kennedy-Shafer; Assistant Professor Mathematics and Statistics, Vassar 
- Colette Salyk; Assistant Professor of Astronomy, Vassar 
- Babak Shahbaba; Professor of Statistics and Computer Science, UCI 
- Joachim Vandekerckhove; Professor of Cognitive Sciences and Statistics, UCI 
- Allison Horst; Assistant Teaching Professor, University of California Santa Barbara 
- Alicia Johnson; Associate Professor of Statistics, Macalester College 
- Joshua Rosenberg; Assistant Professor of STEM education, University of Tennessee 
- Uroš Seljak; Professor of Physics and Astronomy, University of California Berkeley 
- Xin (Cynthia) Tong; Associate Professor of Psychology, University of Virginia 

## Graduate Student Researchers

- [Federica Zoe Ricci](https://federicazoe.github.io/); PhD Student, University of California Irvine

## Participating Faculty

### 2023 Cohort

17 faculty participated in the program. Below are names of some of our participants.

- Abraham Ayebo, Associate Professor, Center for Learning Innovation, University of Minnesota

- Ian Clough, Associate Professor, Math, Computers, Geology & Physics Department, University of Cincinnati Clermont

- Zachary del Rosario, Assistant Professor of Engineering and Applied Statistics, Olin College of Engineering

- Angela Ebeling, Professor, Department of Biology, Wisconsin Lutheran College

- Katie Fitzgerald, Assistant Professor, Department of Mathematics, Physics & Statistics, Azusa Pacific University

- Luella Fu, Assistant Professor, Department of Mathematics, San Francisco State University

- Olga Glebova, Associate Professor, Department of Computer Science, University of Connecticut

- Hasan Hamdan, Professor and Chair of Statistics, James Madison University 

- Coby Klein, Lecturer, Department of Biological Sciences, SUNY Old Westbury

- Stefani Langehennig, Assistant Professor of the Practice, Daniels College of Business, University of Denver
 
- Jody Paul, Professor of Computer Science, Metropolitan State University of Denver

- Samantha Seals, Associate Professor, Department of Mathematics and Statistics, University of West Florida

- Toni Sorrell, Associate Professor, Department of Mathematics & Computer Science, Longwood University

- Patricia Toledo, Associate Professor, Department of Economics, Ohio University

